In [2]:
import sys
import os
import argparse
import numpy as np
import json


In [4]:
# test np.random.normal
shape = (5, 10)
test_rand_matrix = np.random.normal(0, 0.1, size = shape)
print(test_rand_matrix)
print(test_rand_matrix.shape)

[[ 0.02938439 -0.00837927  0.03701083  0.02592763 -0.13098356  0.02176749
   0.01146597 -0.01899485 -0.19790851 -0.15880463]
 [ 0.21755079 -0.05989037 -0.02444523  0.0066403   0.05313161  0.00593874
  -0.0118831  -0.02166014 -0.14899592 -0.12084837]
 [-0.10837655  0.02194826 -0.09289867 -0.07628908 -0.09780317  0.05113322
   0.17632789 -0.07327587 -0.14078447  0.04239597]
 [ 0.11774033  0.06371223 -0.0108545  -0.10230228 -0.0003291   0.04329244
  -0.08109772 -0.19189023 -0.15510948  0.11573984]
 [ 0.01488795 -0.04246038 -0.10342778  0.09956814 -0.06753435  0.19114693
  -0.03522358 -0.10984844  0.10718706  0.1312268 ]]
(5, 10)


In [6]:
# test np.zeros
shape = (5, 10)
test_zeros_matrix = np.zeros(shape)
print(test_zeros_matrix)
print(test_zeros_matrix.shape)

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]
(5, 10)


In [14]:
# test tanh function 
X = np.arange(1,10)
forward_output = (2/(1 + np.exp(-2*X)))
print(forward_output)

[ 1.76159416  1.96402758  1.99505475  1.9993293   1.9999092   1.99998771
  1.99999834  1.99999977  1.99999997]


In [20]:
x = np.random.randint(0, 2, 10)
mask = (x > 0)*1
print(x)
print(mask)

[1 0 1 1 0 1 0 1 1 0]
[1 0 1 1 0 1 0 1 1 0]
